GET http://localhost:3003/api/blogs

###
POST http://localhost:3003/api/blogs/ HTTP/1.1
content-type: application/json

{
    "title": "New Blog 22 Oct",
    "author": "John Smith",
    "url": "random.blog/post/2",
    "likes": 0
}